# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5ee2ed3a139b23549a269a866d3fb71ea0ab32f6298c50da20dd035ff509feb5c680fd296c47574fdfcc569bb82cb14249b246439aef4e6e82b680fbac5d43

test:
  secret_key_base: b2b85c49539931feb3a12cc6dc83b4b2299d57962e084a8a2471ed742a9977421e768db2c9b2e71f12538b133d059bd1c9367f5cb99b09bb9ecb465b02e0b6ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
